name: violencias
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/icons/LogoPoliBlanco.png
    - assets/icons/Recurso 4.png
    - assets/icons/Recurso 5.png
    - assets/icons/Recurso 6.png
    - assets/icons/Recurso 10.png
    - assets/icons/Recurso 7.png
    - assets/icons/Recurso 8.png
    - assets/icons/recurso3.png
    - assets/images/pretty-serious.jpg
    - assets/images/Mujer2.jpg
    - assets/images/Mujer fondo morado.jpg
    - assets/images/home.png
    - assets/images/purple-texture.jpg

  fonts:
    - family: AmsiPro
      fonts:
        - asset: assets/fonts/AmsiPro-Regular.otf
        - asset: assets/fonts/AmsiPro-Ultra.otf
        - asset: assets/fonts/AmsiProNormal-Black.ttf
    - family: LeagueSpartan
      fonts:
        - asset: assets/fonts/LeagueSpartan-Bold.otf

  uses-material-design: true
